#!/bin/sh

set -e

usage() {
    echo "usage: git-rebase-branch-prefix [-h] [-i] [-p] [-f] <branch-prefix> <rebase-branch>"
}

while getopts "hipf" opt; do
    case "${opt}" in
        h)
            usage
            exit 2
            ;;
        i)
            interactive=-i
            ;;
        p)
            push=1
            ;;
        f)
            force=-f
            ;;
        *)
            break
            ;;
    esac
done
shift $((OPTIND -1))

if [ $# -ne 2 ]; then
    usage
    exit 2
fi

branchprefix=${1}
rebasebranch=${2}

# parse the branches out
branches=$(git branch | cut -c 3- | grep "^${branchprefix}")
for b in ${branches} ; do
    git submodule update --init --recursive
    git checkout "${b}"
    git submodule update --init --recursive
    git rebase ${interactive} "${rebasebranch}"
    git submodule update --init --recursive
    if [ "${push}" = "1" ]; then
        git push ${force} origin "${b}"
    fi
done
