#!/bin/sh
#
# @todo add an option to enable a force push to origin (or somewhere else)
#       "--push origin"

set -e

branchprefix=devel-
if [ "${1}" != "" ]; then
    branchprefix=${1}
fi

# parse the branches out
branches=$(git branch | cut -c 3- | grep "^${branchprefix}")
for b in ${branches} ; do
    git checkout "${b}"
    git rebase master
#    git push -f origin "${b}"
done
